---
meta:
  <<: (( merge ))
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent 
    version: latest
  availability_zone: (( merge ))

jobs:
  - name: ingestor
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(7) ))

  - name: queue
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(8) ))

  - name: parser
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(9) ))

  - name: elasticsearch_persistent
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(10) ))

  - name: elasticsearch_autoscale
    instances: 1
    networks:
      - name: default
        static_ips: (( static_ips(11) ))

compilation:
  cloud_properties:
    instance_type: c3.large

resource_pools:
  - name: tiny
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "m3.medium" ))
      elbs: ~

  - name: medium
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "m3.medium" ))
      elbs: ~

  - name: high_cpu
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "c3.large" ))
      elbs: ~

  - name: high_memory
    cloud_properties:
      availability_zone: (( merge || meta.availability_zone ))
      instance_type: (( merge || "m3.large" ))
      elbs: ~

networks: (( merge ))
